<?php if ($this->fortressGuildList): ?>
<div class="margin-top-30">
	<h3><?= $this->translate('Fortress') ?></h3>
	<hr/>
	<ul class="list-unstyled">
        <?php
            $fortressMapping = [
                1 => 'JG Fortress',
                3 => 'HT Fortress',
                4 => 'CT Fortress',
                6 => 'BT Fortress',
        ];
        ?>
		<?php foreach ($this->fortressGuildList as $fortress) :
            /** @var $fortress \GameBackend\Entity\SRO\Shard\SiegeFortress */
        ?>
            <li>
                <strong><?= $this->escapeHtml($fortressMapping[$fortress->getId()]) ?>:</strong>
                <?php if (!$fortress->getGuild() || $fortress->getGuild()->getId() < 1) : ?>
                    <span class="text-primary">
                        <?= $this->translate('Not occupied') ?>
                    </span>
                <?php else : ?>
                    <a class="text-primary" href="<?= $this->url('PServerRanking/guild', ['id' => $fortress->getGuild()->getId()]) ?>">
                        <?= $this->escapeHtml($fortress->getGuild()->getName()) ?>
                    </a>
                <?php endif; ?>
            </li>
		<?php endforeach ?>
	</ul>
</div>
<?php endif; ?>